Fix YAML dump error
```/Users/crispymtn-ms/Repositories/zai-docs/node_modules/js-yaml/index.js:10
    throw new Error('Function yaml.' + from + ' is removed in js-yaml 4. ' +
          ^

Error: Function yaml.safeDump is removed in js-yaml 4. Use yaml.dump instead, which is now safe by default.
    at Object.safeDump (/Users/crispymtn-ms/Repositories/zai-docs/node_modules/js-yaml/index.js:10:11)
    at /Users/crispymtn-ms/Repositories/zai-docs/scripts/fetchDocs.js:142:22
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /Users/crispymtn-ms/Repositories/zai-docs/scripts/fetchDocs.js:137:11
    at async asyncForEach (/Users/crispymtn-ms/Repositories/zai-docs/scripts/fetchDocs.js:9:5)
    at async AppDocs.createReferences (/Users/crispymtn-ms/Repositories/zai-docs/scripts/fetchDocs.js:127:5)
    at async AppDocs.create (/Users/crispymtn-ms/Repositories/zai-docs/scripts/fetchDocs.js:191:24)
    at async /Users/crispymtn-ms/Repositories/zai-docs/scripts/fetchDocs.js:223:3
    at async asyncForEach (/Users/crispymtn-ms/Repositories/zai-docs/scripts/fetchDocs.js:9:5)```